In [1]:
import torch

In [32]:
x = torch.tensor([1,2,3,4], dtype = torch.float32,requires_grad =True)
y = torch.tensor([3,4,7,8], dtype = torch.float32,requires_grad =True)
z = torch.dot(x,y)**2
w = torch.sum(x*y)

In [18]:
# These are the loss functions
print(type(z.grad_fn))
print(type(w.grad_fn))

<class 'PowBackward0'>
<class 'SumBackward0'>


In [25]:
"""
z is like the loss function here. 
A single call to backward() function evaluates the gradients w.r.t the inputs to them.
In this case, it is w.r.t the inputs, that are x and y. backward() function call leads to gradient calculation w.r.t them.
"""
print("Run this cell twice to see the gradient accumulation.")
print("Before .backward() call: (Default None)")
print(x.grad)
print(y.grad)

"""
By default, PyTorch frees the buffers and the computation graph after a .backward() call to save memory.
 When set to True, the intermediate tensors and the graph structure are preserved, 
 allowing you to call .backward() multiple times on the same graph. However, you can see gradient getting accumulated
"""
z.backward(retain_graph=True) 
print("After .backward() call")
print(x.grad)
print(y.grad)

"""
To avoid gradient accumulation, use loss.zero_grad. (Only when you use optimizer)
Here, we will need to explicitly make gradients as None
"""
x.grad = None
y.grad = None

Run this cell twice to see the gradient accumulation.
Before .backward() call: (Default None)
None
None
After .backward() call
tensor([ 384.,  512.,  896., 1024.])
tensor([128., 256., 384., 512.])


In [33]:
print("Run this cell twice to see the gradient accumulation.")
print("Before .backward() call: (Default None)")
print(x.grad)
print(y.grad)

"""
By default, PyTorch frees the buffers and the computation graph after a .backward() call to save memory.
 When set to True, the intermediate tensors and the graph structure are preserved, 
 allowing you to call .backward() multiple times on the same graph. However, you can see gradient getting accumulated
"""
z.backward(retain_graph=True) 
print("\nAfter z.backward() call")
print(x.grad)
print(y.grad)


"""You can see gradient accumulation here. One of the uses of retain_graph is to be 
able to use multiple loss function on the same input"""
w.backward()
print("\nAfter w.backward() call")
print(x.grad)
print(y.grad)

Run this cell twice to see the gradient accumulation.
Before .backward() call: (Default None)
None
None

After z.backward() call
tensor([ 384.,  512.,  896., 1024.])
tensor([128., 256., 384., 512.])

After w.backward() call
tensor([ 387.,  516.,  903., 1032.])
tensor([129., 258., 387., 516.])


In [36]:
z = torch.dot(x,y)**2
print("Run this cell twice to see the gradient accumulation.")
print("Before .backward() call: (Default None)")
print(x.grad)
print(y.grad)

"""
By default, PyTorch frees the buffers and the computation graph after a .backward() call to save memory.
 When set to True, the intermediate tensors and the graph structure are preserved, 
 allowing you to call .backward() multiple times on the same graph. However, you can see gradient getting accumulated
"""
z.backward() 
print("\nAfter z.backward() call")
print(x.grad)
print(y.grad)

Run this cell twice to see the gradient accumulation.
Before .backward() call: (Default None)
tensor([1155., 1540., 2695., 3080.])
tensor([ 385.,  770., 1155., 1540.])

After z.backward() call
tensor([1539., 2052., 3591., 4104.])
tensor([ 513., 1026., 1539., 2052.])
